"""
Django settings for myBoke project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""
import sys
import os




# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(0,os.path.join(BASE_DIR,'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm50szy4)60j^qu!@do*np8685u5b8@5mk#kg%#(t%z19jdm_8)'

# SECURITY WARNING: don't run with debug turned on in production!

#开启404，503等配置
# DEBUG = False
# ALLOWED_HOSTS = ['*']
# STATIC_ROOT =os.path.join(BASE_DIR,'static')

#
STATIC_ROOT= '/static/'
# DEBUG = True
# ALLOWED_HOSTS = []
DEBUG = False
ALLOWED_HOSTS = ['127.0.0.1', 'localhost ', '.huangfeixiang.com']


#邮箱登录
AUTHENTICATION_BACKENDS=(
    'users.views.CustomBackend',
)


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #用户app
    'users',
    #文章分类app
    'Category',
    #后台管理
    'xadmin',
    'crispy_forms',

    'captcha',
    'pure_pagination',

    #集成百度富文本
    'DjangoUeditor',

    #ck富文本
    # 'ckeditor',

    #markdown编辑
    'markdownx',
    'rest_framework'
]

#重载django默认的user表
AUTH_USER_MODEL="users.UserProfile"

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myBoke.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'myBoke.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

#配置数据库，键是固定的
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'newboke',
        'USER': 'root',
        'PASSWORD':'MYSQL366459',
        'HOST':'127.0.0.1',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_L10N = True
#
# USE_TZ = True

#中文
LANGUAGE_CODE = 'zh-hans'

#时区
TIME_ZONE = 'Asia/Shanghai'

#使用本地时间
USE_TZ = False

USE_I18N = True

USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

#发送邮箱配置
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT= 25
#发送方账号
EMAIL_HOST_USER = "pub_fei_xiang2017@163.com"
#第三方授权登录密码
EMAIL_HOST_PASSWORD = "SQM366459"
EMAIL_USE_TLS = False
EMAIL_FROM = "pub_fei_xiang2017@163.com"




STATIC_URL = '/static/'


#指明静态资源目录路径
MEDIA_URL='/media/'
MEDIA_ROOT =os.path.join(BASE_DIR,'media')

#加载静态文件目录(css样式)，
STATICFILES_DIRS= [
    os.path.join(BASE_DIR,'static')
]

#markdown配置
# MARKDOWNX_UPLOAD_URLS_PATH='static/'

#markdown图片文件目录
MARKDOWNX_MEDIA_PATH="markdownx/"

#加载markdown扩展
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    'markdown.extensions.sane_lists',
    'markdown.extensions.nl2br',
    'markdown.extensions.extra',
    'markdown.extensions.tables'
]


MARKDOWNX_URLS_PATH = '/markdownx/markdownify/'
OWNX_EDITOR_RESIZABLE  =  True



#CK富文本配置

# CKEDITOR_UPLOAD_PATH='/media/'
# CKEDITOR_FILENAME_GENERATOR = '/media/'
#
# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'full',
#         # 'extraPlugins':'codesnippet'
#     },
# }



