# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='Comment_Bury',
            field=models.CharField(default='', max_length=500, verbose_name='评论反对id'),
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='Comment_Digg',
            field=models.CharField(default='', max_length=500, verbose_name='评论点赞id'),
        ),
    ]
