# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0006_auto_20170821_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='ReplyComent_id',
            field=models.IntegerField(default='', max_length=16, verbose_name='回复ID'),
        ),
    ]
