# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0007_articlecomments_replycoment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='ReplyComent_id',
            field=models.IntegerField(default='', verbose_name='回复ID'),
        ),
    ]
