# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0009_auto_20170822_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomments',
            name='ReplyComent_id',
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='Comment_BuryID',
            field=models.CharField(default='', max_length=500, verbose_name='评论反对id'),
        ),
    ]
