# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0010_auto_20170822_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomments',
            name='Comment_BuryID',
        ),
        migrations.AddField(
            model_name='articlecomments',
            name='ReplyComent_id',
            field=models.IntegerField(default=100, verbose_name='回复'),
        ),
    ]
