# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0011_auto_20170822_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomments',
            name='ReplyComent_id',
        ),
    ]
