# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0012_remove_articlecomments_replycoment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='ReplyComent_id',
            field=models.IntegerField(default=100, verbose_name='回复评论ID'),
        ),
    ]
