# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0022_auto_20170825_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
    ]
