# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord_is_useful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='is_useful',
            field=models.IntegerField(default=1),
        ),
    ]
